name: Build and Push Docker Images

on:
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "master" ]


jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      APP_IMAGE: "quay.io/aleksander124/openshift-php-front"
      DB_IMAGE: "quay.io/aleksander124/openshift-php-db"
      IMAGE_TAG_LATEST: "latest"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set date and build number
        id: date_and_build
        run: |
          echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV
          echo "BUILD_NUMBER=${{ github.run_number }}" >> $GITHUB_ENV

      - name: Login to Quay.io
        run: |
          docker login -u="aleksander124+github_pipelines" -p=${{ secrets.PUSH_SECRET }} quay.io

      - name: Build and push Docker images
        run: |
          docker build -t $APP_IMAGE:$DATE.$BUILD_NUMBER -t $APP_IMAGE:$IMAGE_TAG_LATEST ./my-app
          docker push $APP_IMAGE:$DATE.$BUILD_NUMBER
          docker push $APP_IMAGE:$IMAGE_TAG_LATEST
          
          docker build -t $DB_IMAGE:$DATE.$BUILD_NUMBER -t $DB_IMAGE:$IMAGE_TAG_LATEST ./my-database
          docker push $DB_IMAGE:$DATE.$BUILD_NUMBER
          docker push $DB_IMAGE:$IMAGE_TAG_LATEST